### ISSUE TITLE
Engine deadlock for long running fitness functions

### ISSUE THREAD

**Issue by dyorgio** [jenetics/jenetics#196]
Cpu usage variates during execution.

Maybe relative with: https://github.com/jenetics/jenetics/issues/47
Not sure, but appears that it is happing again...

Lib version 3.7.0, macOs 10.12.4

Sometimes it consumes only 100% cpu, sometimes 200-700% (I have 4 cores (8 HT).
It variates during runtime...Normally 200-300%.

Profiling with VisualVM shows ForkPool Threads (8 total) with 6 stopped.

Stack Trace Dump:
[jstack.txt](https://github.com/jenetics/jenetics/files/945526/jstack.txt)

**Comment by jenetics** [comment]
Can you also post your fitness function. Maybe this is the reason for the blocking.
```
"ForkJoinPool.commonPool-worker-7" #16 daemon prio=5 os_prio=31 tid=0x00007fb04e015800 nid=0x6103 runnable [0x0000700005f0c000]
   java.lang.Thread.State: RUNNABLE
	at REMOVED$$Lambda$5/665576141.apply(Unknown Source)
	at org.jenetics.Phenotype.lambda$new$0(Phenotype.java:118)
	at org.jenetics.Phenotype$$Lambda$28/411631404.get(Unknown Source)
	at org.jenetics.internal.util.Lazy.evaluate(Lazy.java:77)
	- locked <0x00000006c5a2d758> (a org.jenetics.internal.util.Lazy)
	at org.jenetics.internal.util.Lazy.get(Lazy.java:62)
	at org.jenetics.Phenotype.lambda$new$1(Phenotype.java:119)
	at org.jenetics.Phenotype$$Lambda$29/1792845110.get(Unknown Source)
	at org.jenetics.internal.util.Lazy.evaluate(Lazy.java:77)
	- locked <0x00000006c5a2d780> (a org.jenetics.internal.util.Lazy)
	at org.jenetics.internal.util.Lazy.get(Lazy.java:62)
	at org.jenetics.Phenotype.getFitness(Phenotype.java:180)
	at org.jenetics.Phenotype.evaluate(Phenotype.java:140)
	at org.jenetics.Phenotype.run(Phenotype.java:151)
	at org.jenetics.internal.util.RunnablesAction.compute(RunnablesAction.java:73)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
...
"ForkJoinPool.commonPool-worker-1" #10 daemon prio=5 os_prio=31 tid=0x00007fb04aa2c800 nid=0x5703 runnable [0x00007000059fc000]
   java.lang.Thread.State: RUNNABLE
	at REMOVED$$Lambda$5/665576141.apply(Unknown Source)
	at org.jenetics.Phenotype.lambda$new$0(Phenotype.java:118)
	at org.jenetics.Phenotype$$Lambda$28/411631404.get(Unknown Source)
	at org.jenetics.internal.util.Lazy.evaluate(Lazy.java:77)
	- locked <0x00000006c5b814c0> (a org.jenetics.internal.util.Lazy)
	at org.jenetics.internal.util.Lazy.get(Lazy.java:62)
	at org.jenetics.Phenotype.lambda$new$1(Phenotype.java:119)
	at org.jenetics.Phenotype$$Lambda$29/1792845110.get(Unknown Source)
	at org.jenetics.internal.util.Lazy.evaluate(Lazy.java:77)
	- locked <0x00000006c5b814e8> (a org.jenetics.internal.util.Lazy)
	at org.jenetics.internal.util.Lazy.get(Lazy.java:62)
	at org.jenetics.Phenotype.getFitness(Phenotype.java:180)
	at org.jenetics.Phenotype.evaluate(Phenotype.java:140)
	at org.jenetics.Phenotype.run(Phenotype.java:151)
	at org.jenetics.internal.util.RunnablesAction.compute(RunnablesAction.java:73)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:759)
	at org.jenetics.internal.util.RunnablesAction.compute(RunnablesAction.java:77)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
Because two threads are waiting `at REMOVED$$Lambda$5/665576141.apply(Unknown Source)`. The locks at the `Lazy` evaluation objects are all on different instances.

**Comment by jenetics** [comment]
Follow up: #197 
This might be the main reason for this behavior.

**Comment by dyorgio** [comment]
Tks @jenetics !
I think that you are in the right way with issue #197.

My fitness function is a long task (but it has internal optimization to stop during execution).
So, my cenario is a "fitness function with unpredictable computation costs" as you sad in this issue.

I don't use any multi-thread strategy, cache, shared or lock objects inside it.

**Comment by jenetics** [comment]
Yes, I do the changes in a separate branch. A testable version should be available at Sunday evening.

**Comment by jenetics** [comment]
@dyorgio a first version of the fix is available in https://github.com/jenetics/jenetics/tree/issues/JENETICS-197-cpu_utilization for testing.

**Comment by dyorgio** [comment]
After using for a while I can feel a big improvement!

Now, CPU time is 630%-730% (800% max). no more "deadlocks" with threadpool (use only 1 thread - 100% cpu).

**Comment by jenetics** [comment]
Good to hear and thank you for testing.

**Comment by jenetics** [comment]
Fix in now part of r3.8.0 branch.
