### ISSUE TITLE
GP load/save generated tree

### ISSUE THREAD

**Issue by M3talen** [jenetics/jenetics#298]
Is there no way to save/load a generated tree with jenetics.prog ?

using 
`IO.object.write(tree,resultPath);`
throws
`Exception in thread "main" java.io.NotSerializableException: io.jenetics.prog.ProgramGene
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at io.jenetics.util.IO$1.write(IO.java:71)
	at io.jenetics.util.IO.write(IO.java:129)
	at io.jenetics.util.IO.write(IO.java:114)
	at Test2.main(Test2.java:134)`

**Comment by jenetics** [comment]
It seems that I missed to add the `Serializable` interface on some _value_ classes, like `Var` or `Const`. So this is currently not possible.

**Comment by M3talen** [comment]
Thank you for the quick reply but commit [e350c2f](https://github.com/jenetics/jenetics/commit/e350c2f19460d4c04090b9ea589650180bb503e3) does still not solve the issue.
For the supplied test in `ProgramChromosomeTest.java` it throws : 
```
Exception in thread "main" java.io.NotSerializableException: io.jenetics.prog.op.Operation
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at io.jenetics.internal.collection.Array.writeObject(Array.java:350)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at io.jenetics.util.IO$1.write(IO.java:71)
	at Test2.main(Test2.java:120)
```
And for the earlier issue it throws : 
```
Exception in thread "main" java.io.NotSerializableException: io.jenetics.prog.ProgramGene
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at io.jenetics.util.IO$1.write(IO.java:71)
	at Test2.main(Test2.java:149)
```

**Comment by jenetics** [comment]
You are right, but the intention of the commit was to reproduce the error. Sorry, I will fix it a little bit later :-)

**Comment by jenetics** [comment]
Merged into r4.1.0 branch.
