### ISSUE TITLE
test failed: org.jenetics.util.NanoClockTest.millis

### ISSUE THREAD

**Issue by arisliang** [jenetics/jenetics#44]
NanoClockTest.millis test failed with gradle wrapper "clean build jar" tasks.

Second build with "jar" task succeeded.

below is the error message:

java.lang.AssertionError: Got 1435772991847 but expected 1435772997614.
    at org.jenetics.util.NanoClockTest.assertEquals(NanoClockTest.java:46)
    at org.jenetics.util.NanoClockTest.millis(NanoClockTest.java:40)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
    at org.testng.TestRunner.privateRun(TestRunner.java:767)
    at org.testng.TestRunner.run(TestRunner.java:617)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
    at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
    at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
    at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by jenetics** [comment]
Yes, this test is a little brittle in the master branch. It compares the timestamp from the `NanoClock` with the timestamp of the `System.currentTimeMillis()` call. As a side-effect of #24, the test will be retried 3 times before failing: https://github.com/jenetics/jenetics/commit/d891e7d12f0a9768b6bef5d9632bb710dafae9ff#diff-ae73111d4c23bed9b5e1b8e34ec6bb0e

Since then, it never failed on my machine and on https://travis-ci.org/jenetics/jenetics
