### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by arisliang** [jenetics/jenetics#46]
I tried to run the 0/1 Knapsack example coming from user manual, encountered below error.

Line of code that seem to be causing this error:
.collect(EvolutionResult.toBestPhenotype());
which is line 113 on user manual at 0/1 Knapsack example.

Error message:
Exception in thread "main" java.lang.NullPointerException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
	at java.util.concurrent.ForkJoinTask.reportException(Unknown Source)
	at java.util.concurrent.ForkJoinTask.join(Unknown Source)
	at org.jenetics.internal.util.Concurrency$ForkJoinPoolConcurrency.close(Concurrency.java:119)
	at org.jenetics.engine.Engine.evaluate(Engine.java:407)
	at org.jenetics.engine.Engine.evolutionStart(Engine.java:441)
	at org.jenetics.engine.Engine$$Lambda$24/1615780336.get(Unknown Source)
	at org.jenetics.engine.EvolutionSpliterator.tryAdvance(EvolutionSpliterator.java:65)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at knapsack.Knapsack.main(Knapsack.java:41)
Caused by: java.lang.NullPointerException
	at knapsack.Item.lambda$1(Item.java:28)
	at knapsack.Item$$Lambda$40/905606853.accept(Unknown Source)
	at java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source)
	at java.util.stream.IntPipeline$4$1.accept(Unknown Source)
	at java.util.stream.IntPipeline$9$1.accept(Unknown Source)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Unknown Source)
	at java.util.Spliterator$OfInt.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at knapsack.FF.apply(FF.java:23)
	at knapsack.FF.apply(FF.java:1)
	at org.jenetics.Phenotype.eval(Phenotype.java:137)
	at org.jenetics.Phenotype.evaluate(Phenotype.java:130)
	at org.jenetics.Phenotype.run(Phenotype.java:150)
	at org.jenetics.internal.util.RunnablesAction.compute(RunnablesAction.java:73)
	at java.util.concurrent.RecursiveAction.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
	at java.util.concurrent.ForkJoinTask.invokeAll(Unknown Source)
	at org.jenetics.internal.util.RunnablesAction.compute(RunnablesAction.java:77)
	at java.util.concurrent.RecursiveAction.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
	at java.util.concurrent.ForkJoinTask.invokeAll(Unknown Source)
	at org.jenetics.internal.util.RunnablesAction.compute(RunnablesAction.java:77)
	at java.util.concurrent.RecursiveAction.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
	at java.util.concurrent.ForkJoinTask.invokeAll(Unknown Source)
	at org.jenetics.internal.util.RunnablesAction.compute(RunnablesAction.java:77)
	at java.util.concurrent.RecursiveAction.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
	at java.util.concurrent.ForkJoinTask.invokeAll(Unknown Source)
	at org.jenetics.internal.util.RunnablesAction.compute(RunnablesAction.java:77)
	at java.util.concurrent.RecursiveAction.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

**Comment by jenetics** [comment]
Can you attach your actual source code? Otherwise the line numbers in the stack trace are almost useless, especially the _Caused by_ part:
```
Caused by: java.lang.NullPointerException
at knapsack.Item.lambda$1(Item.java:28)
at knapsack.Item$$Lambda$40/905606853.accept(Unknown Source)
at java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source)
at java.util.stream.IntPipeline$4$1.accept(Unknown Source)
...
```
Or if you check out the source code, the `org.jenetics.example` project contains the Knapsack example as in the manual. Then I can compare the line numbers.

* How can I reproduce it? 
* Did this error occur on every run or only from time to time? 
* How many cores has your computer, if its an concurrency issue? 
* You had this error on the actual `master` branch, right?

**Comment by arisliang** [comment]
The source code is below:
-------------
package knapsack2;

import java.util.Random;
import java.util.function.Function;
import java.util.stream.Collector;


import java.util.stream.Stream;


import org.jenetics.BitChromosome;
import org.jenetics.BitGene;
import org.jenetics.Genotype;
import org.jenetics.Mutator;
import org.jenetics.Phenotype;
import org.jenetics.RouletteWheelSelector;
import org.jenetics.SinglePointCrossover;
import org.jenetics.TournamentSelector;
import org.jenetics.engine.Engine;
import org.jenetics.engine.EvolutionResult;
import org.jenetics.engine.EvolutionStatistics;
import org.jenetics.engine.limit;
import org.jenetics.util.RandomRegistry;

final class Item {
	public final double size;
	public final double value;

	Item(double size, double value) {
		super();
		this.size = size;
		this.value = value;
	}

	// Create a new random knapsack item
	static Item random() {
		final Random r = RandomRegistry.getRandom();
		return new Item(r.nextDouble() * 100, r.nextDouble() * 100);
	}

	// Create a new collector for summing up the knapsack items.
	static Collector<Item, ?, Item> toSum() {
		return Collector.of(
				() -> new Double[2],
				(a, b) -> {a[0] += b.size;a[1] += b.value;},
				(a, b) -> {a[0] += b[0]; a[1] += b[1];return a;},
				r -> new Item(r[0], r[1]));
	}
}

//The knapsack fitness function class, which is parametrized
//with the available items and the size of the knapsack. 
final class FF implements Function<Genotype<BitGene>, Double> {
	private final Item[] items;
	private final double size;

	public FF(final Item[] items, final double size) {
		super();
		this.items = items;
		this.size = size;
	}

	@Override
	public Double apply(final Genotype<BitGene> gt) {
		final Item sum = ((BitChromosome) gt.getChromosome()).ones()
				.mapToObj(i -> items[i])
				.collect(Item.toSum());

		return sum.size <= this.size ? sum.value : 0;
	}
}

//The main class
public class Knapsack {

	public static void main(String[] args) {
		final int nitems = 15;
		final double kssize = nitems * 100.0 / 3.0;

		final FF ff = new FF(Stream.generate(Item::random)
				.limit(nitems)
				.toArray(Item[]::new),
				kssize);
		
		// Configure and build the evolution engine.
		final Engine<BitGene, Double> engine = Engine
				.builder(ff, BitChromosome.of(nitems, 0.5))
				.populationSize(500)
				.survivorsSelector(new TournamentSelector<>(5))
				.offspringSelector(new RouletteWheelSelector<>())
				.alterers(new Mutator<>(0.115),
						new SinglePointCrossover<>(0.16))
				.build();
		
		// Create evolution statistics consumer.
		final EvolutionStatistics<Double, ?> statistics = EvolutionStatistics.ofNumber();
		
		final Phenotype<BitGene, Double> best = engine.stream()
				// Truncate the evolution stream after 7 "steady" generations.
				.limit(limit.bySteadyFitness(7))
				// The evolution will stop after maximal 100 generations
				.limit(100)
				// Update the evaluation statistics after each generation
				.peek(statistics)
				// Collect (reduce) the evolution stream to its best phenotype.
				.collect(EvolutionResult.toBestPhenotype());
		
		System.out.println(statistics);
		System.out.println(best);
	}

}

**Comment by arisliang** [comment]
Strangely though, I copy and paste the code to run in IntelliJ, it runs successfully. The error message was in Eclipse 4.4.2.

**Comment by jenetics** [comment]
If the error occurs on every run with Eclipse, I would blame the Eclipse compiler/environment for the error. Eclipse still has problems with "lambafied" code, which is also mentioned in the README. This is one of the reasons for using IntelliJ instead of Eclipse.

For further investigations, I would need this (somehow) reproducible with the Java compiler (javac) on the commandline.

**Comment by arisliang** [comment]
I'm not sure how to upload the source code here, so I created a new repository (https://github.com/arisliang/KnapsackError) and a minimum case there, together with compile and run script. Hope it helps.

**Comment by jenetics** [comment]
Thank your, now I could reproduce it. There is quite a subtle problem with _your_ example code. The bug is in the `Item.toSum` method:

```java
static Collector<Item, ?, Item> toSum() {
	return Collector.of(
		// You create a 'Double' object array instead of
		// a 'double' primitive type array. The object array 
		// will be initialized with 'null', which caused the NPE.
		// The 'double' array is initialized with zeros.
		() -> new Double[2], // Replace this with '() -> new double[2]'
		(a, b) -> {a[0] += b.size;a[1] += b.value;},
		(a, b) -> {a[0] += b[0]; a[1] += b[1];return a;},
		r -> new Item(r[0], r[1]));
}
```

A single character, 'd' instead of 'D', makes the difference.

**Comment by arisliang** [comment]
Thank you, you're absolutely right. Confirmed that this was a code error, not related to Eclipse / Jenetics. Could've avoided if being a bit more careful when I typed them in.
