### ISSUE TITLE
Engine deadlock for long running fitness functions

### ISSUE THREAD

**Issue by jenetics** [jenetics/jenetics#47]
For long running fitness functions, the Engine might get stuck in the `Phenotype.run()` function.
```
"ForkJoinPool.commonPool-worker-13" #14 daemon prio=5 os_prio=0 tid=0x00007ff3401c7000 nid=0x52ec waiting on condition [0x00007ff312a21000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007229e13a0> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1685)
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3310)
	at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1721)
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1926)
	at org.jenetics.engine.Engine.evolve(Engine.java:303)
	at org.jenetics.engine.Engine$$Lambda$38/596512129.apply(Unknown Source)
	at org.jenetics.engine.EvolutionSpliterator.tryAdvance(EvolutionSpliterator.java:68)
	at java.util.Spliterator.forEachRemaining(Spliterator.java:326)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.jenetics.engine.StreamProxy.collect(StreamProxy.java:83)
	at org.jenetics.optimizer.EngineOptimizer.opt(EngineOptimizer.java:123)
	at org.jenetics.optimizer.EngineOptimizer$$Lambda$24/1198108795.apply(Unknown Source)
	at java.util.function.Function.lambda$andThen$6(Function.java:88)
	at java.util.function.Function$$Lambda$25/214126413.apply(Unknown Source)
	at org.jenetics.Phenotype.eval(Phenotype.java:137)
	- locked <0x0000000722d92318> (a org.jenetics.Phenotype)
	at org.jenetics.Phenotype.evaluate(Phenotype.java:130)
	at org.jenetics.Phenotype.run(Phenotype.java:150)
	at org.jenetics.internal.util.RunnablesAction.compute(RunnablesAction.java:73)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:759)
	at org.jenetics.internal.util.RunnablesAction.compute(RunnablesAction.java:77)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

"ForkJoinPool.commonPool-worker-4" #13 daemon prio=5 os_prio=0 tid=0x00007ff2b0001000 nid=0x52eb waiting on condition [0x00007ff312b22000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000722648a30> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1685)
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3310)
	at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1721)
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1926)
	at org.jenetics.engine.Engine.evolve(Engine.java:303)
	at org.jenetics.engine.Engine$$Lambda$38/596512129.apply(Unknown Source)
	at org.jenetics.engine.EvolutionSpliterator.tryAdvance(EvolutionSpliterator.java:68)
	at java.util.Spliterator.forEachRemaining(Spliterator.java:326)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.jenetics.engine.StreamProxy.collect(StreamProxy.java:83)
	at org.jenetics.optimizer.EngineOptimizer.opt(EngineOptimizer.java:123)
	at org.jenetics.optimizer.EngineOptimizer$$Lambda$24/1198108795.apply(Unknown Source)
	at java.util.function.Function.lambda$andThen$6(Function.java:88)
	at java.util.function.Function$$Lambda$25/214126413.apply(Unknown Source)
	at org.jenetics.Phenotype.eval(Phenotype.java:137)
	- locked <0x0000000722d63fb0> (a org.jenetics.Phenotype)
	at org.jenetics.Phenotype.evaluate(Phenotype.java:130)
	at org.jenetics.Phenotype.run(Phenotype.java:150)
	at org.jenetics.internal.util.RunnablesAction.compute(RunnablesAction.java:73)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool.helpStealer(ForkJoinPool.java:1955)
	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2044)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:390)
	at java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:761)
	at org.jenetics.internal.util.RunnablesAction.compute(RunnablesAction.java:77)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by jenetics** [comment]
Do the evaluation of the fitness function at the beginning of the 'evolve' step.

**Comment by dyorgio** [comment]
Not sure, but appears that it is happing again...
version 3.7.0, macOs 10.12.4

Sometimes it consumes only 100% cpu, sometimes 200-600% (I have 4 cores (8 HT).
It variates during runtime...

**Comment by jenetics** [comment]
If it happened again, can you create a thread-dump (`jstack -l <pid> > jstack.out`), create a new bug ticket and add the dump. Ideally, you could add also some code (unit-test) which makes the error reproducible.

Thanks, Franz
