### ISSUE TITLE
DynamicGenotype example causes IllegalArgumentException

### ISSUE THREAD

**Issue by javagl** [jenetics/jenetics#473]
First of all: Kudos for this library. It's great to see such a well-documented and carefully crafted library with many examples.

I'm just getting started, and was "browsing" through the samples, so cannot give too many details about the context, but noticed that the `DynamicGenotype` example at https://github.com/jenetics/jenetics/blob/17ee6f50ae91846c6a4b2870b7c2ee3b34d3f41f/jenetics.example/src/main/java/io/jenetics/example/DynamicGenotype.java throws an `IllegalArgumentException` at some point:

    ...
    Gene count: 214
    Gene count: 236
    Exception in thread "main" java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Number of genes (16) not within the allowed range: [17, 18]
        at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
        at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
        at java.util.concurrent.CompletableFuture.uniApply(Unknown Source)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
        at java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
    Caused by: java.lang.IllegalArgumentException: Number of genes (16) not within the allowed range: [17, 18]
        at io.jenetics.VariableChromosome.checkLengthRange(VariableChromosome.java:84)
        at io.jenetics.VariableChromosome.<init>(VariableChromosome.java:61)
        at io.jenetics.AbstractBoundedChromosome.<init>(AbstractBoundedChromosome.java:73)
        at io.jenetics.DoubleChromosome.<init>(DoubleChromosome.java:74)
        at io.jenetics.DoubleChromosome.newInstance(DoubleChromosome.java:133)
        at io.jenetics.DoubleChromosome.newInstance(DoubleChromosome.java:48)
        at io.jenetics.example.DynamicGenotype$DynamicMutator.mutate(DynamicGenotype.java:132)
        at io.jenetics.example.DynamicGenotype$DynamicMutator.lambda$1(DynamicGenotype.java:120)
        at java.util.stream.IntPipeline$3$1.accept(Unknown Source)
        at java.util.stream.IntPipeline$9$1.accept(Unknown Source)
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Unknown Source)
        at java.util.Spliterator$OfInt.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.IntPipeline.reduce(Unknown Source)
        at java.util.stream.IntPipeline.sum(Unknown Source)
        at io.jenetics.example.DynamicGenotype$DynamicMutator.mutate(DynamicGenotype.java:121)
        at io.jenetics.example.DynamicGenotype$DynamicMutator.lambda$0(DynamicGenotype.java:92)
        at java.util.stream.ForEachOps$ForEachOp$OfInt.accept(Unknown Source)
        at java.util.stream.IntPipeline$9$1.accept(Unknown Source)
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Unknown Source)
        at java.util.Spliterator$OfInt.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfInt.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.IntPipeline.forEach(Unknown Source)
        at io.jenetics.example.DynamicGenotype$DynamicMutator.alter(DynamicGenotype.java:88)
        at io.jenetics.engine.Engine.lambda$evolve$2(Engine.java:298)
        at io.jenetics.engine.TimedResult.lambda$of$1(TimedResult.java:81)
        ... 7 more

There's some randomness involved, obviously, but it seems to always be reproducible.

**Comment by jenetics** [comment]
Thank you for the report. The error is in the example itself. The `mutate` method changes the length of the chromosome, without checking the allowed length.

```java
// Add/remove Chromosome to Genotype.
final Random random = RandomRegistry.getRandom();
final double rd = random.nextDouble();
if (rd < 1/3.0) {
	chromosomes.remove(0);
} else if (rd < 2/3.0) {
	chromosomes.add(chromosomes.get(0).newInstance());
}
```

**Comment by jenetics** [comment]
Merged into r5.0.0 branch.
