### ISSUE TITLE
Wrond bounds at io.jenetics.prog.regression.Sample.argAt

### ISSUE THREAD

**Issue by savinov-anton-v** [jenetics/jenetics#550]
Implementation of io.jenetics.prog.regression.Sample.argAt has wrong boundary check.
For example, Sample.ofDouble(x, y) will store 2 items in _sample attribute.
Call of the arity() will return 1, because it calculates as _sample.length - 1.
Call of the argAt(final int index) with 0 values as an argument will thrown an exception, but should return an "x" (_sample[0]).  Implementation of the "argAt" should be changed in order to use "index < 0 || index >= arity()" instead of "index < 0 || index >= arity() - 1".

This applies to all implementations of io.jenetics.prog.regression.Sample:
1. DoubleSample
2. ObjectSample

**Comment by jenetics** [comment]
```java
@Test
public void argAt() {
	final Sample<Double> s = Sample.ofDouble(1.0, 2.0);
	System.out.println(s.argAt(0) + ":" + s.arity());
}
```
```
java.lang.ArrayIndexOutOfBoundsException: Argument index out or range [0, 1): 0
	at io.jenetics.prog.regression.DoubleSample.argAt(DoubleSample.java:66)
	at io.jenetics.prog.regression.DoubleSample.argAt(DoubleSample.java:33)
	at io.jenetics.prog.regression.LossFunctionTest.foo(LossFunctionTest.java:33)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by jenetics** [comment]
@savinov-anton-v Thank you for the bug report.

**Comment by jenetics** [comment]
Fixed and merged into r5.0.1 branch.
