### ISSUE TITLE
Exception at io.jenetics.prog.regression.Samples.<init>

### ISSUE THREAD

**Issue by savinov-anton-v** [jenetics/jenetics#554]
Using code example from http://jenetics.io/javadoc/jenetics.prog/5.0/index.html produces:
Caused by: java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [[Ljava.lang.Object;
	at io.jenetics.prog.regression.Samples.<init>(Samples.java:46)
	at io.jenetics.prog.regression.Regression.of(Regression.java:193)
	at io.jenetics.prog.regression.Regression.of(Regression.java:216)
	at investigation.jenetics.JeneticsTest4.<clinit>(JeneticsTest4.java:42)
	... 22 more

Error is inside this block:
``` java
_arguments = (T[][])_samples.stream()
  .map(Samples::args)
  .toArray();
```
Samples::args returns T[], and .toArray() should be T[][]. So, type conversion is true in meaning, but erroneous at runtime.

**Comment by savinov-anton-v** [comment]
Reproducible in 5.0.1 branch, because you need https://github.com/jenetics/jenetics/issues/550 be fixed in order to reach this step.

**Comment by jenetics** [comment]
Thank you, @savinov-anton-v , for testing the `regression` package. ;-)

**Comment by jenetics** [comment]
Merged into r5.0.1 branch. The `SymbolicRegression` example should work now.

@savinov-anton-v ready to check :smiley:
