### ISSUE TITLE
Fix BitChromosome(Test)

### ISSUE THREAD

**Issue by jenetics** [jenetics/jenetics#836]
```
Gradle suite > Gradle test > io.jenetics.BitChromosomeTest > toBigInteger[23](00000001|11111111|10001011|11101100|10001100|11000010|10000000|10111100|10011101|11000110|11011111|11011111|00111000|11010111|00111100|01111110|10000010|10001101|01011101|01010001|01001111|01000100|00111110|00001000|01001100|00101111|11110011|01111110|11010011|01000100|10110001|11000010|01010110|00110110|00101000|10101111|01000011|10011101) FAILED
    java.lang.AssertionError: expected [00000001|11111111|10001011|11101100|10001100|11000010|10000000|10111100|10011101|11000110|11011111|11011111|00111000|11010111|00111100|01111110|10000010|10001101|01011101|01010001|01001111|01000100|00111110|00001000|01001100|00101111|11110011|01111110|11010011|01000100|10110001|11000010|01010110|00110110|00101000|10101111|01000011|10011101] but found [00000001|00000000|10001011|11101100|10001100|11000010|10000000|10111100|10011101|11000110|11011111|11011111|00111000|11010111|00111100|01111110|10000010|10001101|01011101|01010001|01001111|01000100|00111110|00001000|01001100|00101111|11110011|01111110|11010011|01000100|10110001|11000010|01010110|00110110|00101000|10101111|01000011|10011101]
        at org.testng.Assert.fail(Assert.java:99)
        at org.testng.Assert.failNotEquals(Assert.java:1037)
        at org.testng.Assert.assertEqualsImpl(Assert.java:140)
        at org.testng.Assert.assertEquals(Assert.java:122)
        at org.testng.Assert.assertEquals(Assert.java:617)
        at io.jenetics.internal.util.EquivalentValidator.verify(EquivalentValidator.java:41)
        at io.jenetics.BitChromosomeTest.toBigInteger(BitChromosomeTest.java:151)
```

**Comment by jenetics** [comment]
Merged into r7.1.0 branch.
